title: Gamer Assistants - esports , csgo , lol 
baseline: esports players assistant - it is me
description:  Your writing maniac about esport business and expansion games and much more
baseurl: /
canonicalurl: true
keywords: [esports, csgo , lol , e-sports world, tips]
author: G2 and Team Liquid Team League of Legens Ligny
language: en
languages:
  - code: en
    locale: en
  - code: fr
    locale: fr_FR
    config:
      baseline: esports player's assistant - it is me
      description:esports player's assistant - it is me 
      taxonomies:
        tags: esports  
theme:
  - hyde
  - netlify
  - netlify-cms
hyde:
  sidebar:
    sticky: true  # Content to the bottom of the sidebar
  theme: ''       # red, orange, yellow, green, cyan, blue, magenta, brown or cecil
  reverse: false  # Reverse layout
  fonts: 'google' # google or local

body:
  highlight:
    enabled: true
  images:
    lazy:
      enabled: true
    resize:
      enabled: true
    responsive:
      enabled: true
    webp:
      enabled: true
    caption:
      enabled: true
assets:
  images:
    optimize:
      enabled: true
    quality: 75
    responsive:
      enabled: true
      responsive:
      widths: [768, 1024]
      sizes:
        default: "(max-width: 608px) 768px, 1024px"
    webp:
      enabled: true
